### ISSUE TITLE
node.js environment!!

### ISSUE THREAD

**Issue by macCesar** [danbovey/fontname#1]
Hi there!!

This is exactly what I need.. the only problem is that I need it to work on a `node.js` environment, not on the web.

Is there a way to read the font file directly without the need to use `FileReader ` ??

What I'm most interested is getting the `postScriptName ` of the font.

Thanks!!!

**Comment by macCesar** [comment]
I think I got it!!

```javascript
const fs = require('fs');
const FontName = require('fontname');
let fontMeta = FontName.parse(fs.readFileSync(`font-file-location`))[0];
console.log(fontMeta);
```

```javascript
{
  copyright: 'Created by Jordan Humphreys with FontForge 2.0 (http://fontforge.sf.net)',
  _lang: 0,
  fontFamily: 'fontcustom',
  fontSubfamily: 'Medium',
  ID: 'FontForge 2.0 : fontcustom : 23-8-2013',
  fullName: 'fontcustom',
  version: 'Version 001.000 ',
  postScriptName: 'fontcustom'
}
```

**Comment by danbovey** [comment]
Great stuff! I've added this to the README. 👏

**Comment by macCesar** [comment]
Great module, and very handy!!!
